### ISSUE TITLE
安装失败 0x80004005

### ISSUE THREAD

**Issue by Cuberick-Orion** [Scighost/Xunkong#10]
环境

Edition	Windows 11 Pro
Version	21H2
Installed on	‎6/‎29/‎2021
OS build	22000.527
Experience	Windows Feature Experience Pack 1000.22000.527.0

---

安装Preview/Development版本时触发以下error:

```
App installation failed with error message: 
Appinstaller operation failed with error code 0x80004005. 
Detail: Unspecified error (0x80004005)
```

遗憾的是并没有更详细的错误信息……

截图如下
![image](https://user-images.githubusercontent.com/30120549/157377765-52544274-4b69-4259-b34b-f7ee8169069c.png)

**Comment by Scighost** [comment]
下载完整安装包，然后运行ps脚本。
https://scighost-generic.pkg.coding.net/xunkong/releases/Xunkong.Desktop.Package.zip

**Comment by Cuberick-Orion** [comment]
问题解决 多谢
