### ISSUE TITLE
固定动态磁贴时报错

### ISSUE THREAD

**Issue by gongfuture** [Scighost/Xunkong#11]
![image](https://user-images.githubusercontent.com/60888755/157394591-8dfcdad1-9a4f-4b9b-a0cc-478b018da31b.png)
版本更新前原本已经固定，更新后磁贴不更新，移除磁贴后尝试重新添加时报错
且原磁贴不再可点击打开寻空

**Comment by gongfuture** [comment]
已经移除了磁贴但寻空仍然显示解除磁贴，可能是这个原因？

**Comment by Scighost** [comment]
我觉得可以尝试卸载重装

**Comment by gongfuture** [comment]
重启之后可以再次固定了qwq，估计是windows的问题
