### ISSUE TITLE
更新弹窗不显示下载按键

### ISSUE THREAD

**Issue by MaxwellYe0815** [Scighost/Xunkong#13]
打开寻空时自动弹出的更新提醒无下载按键
手动检查更新正常
![image](https://user-images.githubusercontent.com/64358442/157421696-04f0d8ec-6c71-46b2-8868-b49302818905.png)

**Comment by MaxwellYe0815** [comment]
额
每日下载量超出限制了orz

**Comment by Scighost** [comment]
艹

**Comment by Scighost** [comment]
已改用 CloudFlare
