### ISSUE TITLE
hoyolab 签到/相册功能

### ISSUE THREAD

**Issue by bobjiang6** [Scighost/Xunkong#14]
1、导入网页cookie后可正常显示体力等信息，但无法完成签到/扎记抓取
     报error：hoyolab未登录
2、相册功能报warning 找不到截图文件夹

**Comment by bobjiang6** [comment]
重新登陆的cookies解决了问题1

**Comment by Scighost** [comment]
在设置页面，启动游戏那指定exe文件可以解决问题2 。

**Comment by shikkoku** [comment]
![Screenshot 2022-03-10 123902](https://user-images.githubusercontent.com/4697177/157590869-8259ce77-6f5e-4b0e-a98a-e9ca250be39f.jpg)

我用hoyolab的cookie登录不了
