### ISSUE TITLE
查看祈愿记录卡死问题

### ISSUE THREAD

**Issue by 1578339936** [Scighost/Xunkong#16]
打开祈愿记录大几率卡死

**Comment by Haku247** [comment]
同样问题，大几率卡死。
系统版本：win11 pro for workstation 21H2
版本号: 22000.527
windows功能体验包: 1000.22000.527.0

**Comment by Scighost** [comment]
祈愿记录页面的性能是很差，最好不要有太频繁的操作。

**Comment by tongfuwei** [comment]
希望后续能够优化祈愿页面的性能,目前的体验属实不太好
