### ISSUE TITLE
2020年12月前的数据无法导入

### ISSUE THREAD

**Issue by 924244687** [Scighost/Xunkong#17]
2020年12月前的抽取记录不包含祈愿id。此部分数据由 genshin-wish-export 导出 Json后正常导入刻晴牛杂。
但是通过刻晴牛杂可以导出全部数据后，xlsx文件中可以找到这部分，但是在导入寻空时会被舍弃。

**Comment by Scighost** [comment]
直接使用 刻记牛杂店 UserData 文件夹中的 json 文件导入。
