### ISSUE TITLE
角色一览里重复统计

### ISSUE THREAD

**Issue by yangysc** [Scighost/Xunkong#18]
RT, 9命重云; 五星数目被多统计了一次
这个数字表示实际数目+1的话0命会显示1，其实和米游社的统计方式有点出入。不知道哪种更方便了=。=只不过两个一起看的用户可能不太适应
![image](https://user-images.githubusercontent.com/8980981/157568310-b85c9ec1-40a7-4352-9563-f5789d7ec2c3.png)

**Comment by MaxwellYe0815** [comment]
你有没有考虑过一种可能性，这不是表示命座，而仅仅是表示抽到的个数
我还有精15的祭礼残章呢

**Comment by yangysc** [comment]
> 

虽然但是，我的五星次数都被+1了。。。

**Comment by yangysc** [comment]
貌似这个数字表示实际数目+1？比如0命会显示1？感觉可以参考mys优化一下0命不显示数字，以此为基准再加数字
