### ISSUE TITLE
HoyolabExeption 登录失败，请重新登录（-100）

### ISSUE THREAD

**Issue by GUn2005** [Scighost/Xunkong#19]
![image](https://user-images.githubusercontent.com/66047615/157635621-920974e2-42f3-4562-a866-5c452d8fd3f4.png)
导入的cookie里已包含cookie_token和account_id

**Comment by shikkoku** [comment]
同样登录不了。不开代理报-100 开了代理报SSL错误。

**Comment by GUn2005** [comment]
![image](https://user-images.githubusercontent.com/66047615/157643971-250d7780-23f6-4369-9b0e-d33886961f5b.png)
牛杂店也一样

**Comment by Askwind** [comment]
问题还在啊，为何关闭了，是后期会修复吗？
