### ISSUE TITLE
寻空未来可以会类似可莉特调中-每日素材的功能吗？

### ISSUE THREAD

**Issue by huabozahuopu** [Scighost/Xunkong#2]
每次打开之后就可以清晰看到今天可以刷哪个角色的素材。
现在可莉特调好像没有更新后面的内容了，而且目前也没找到别的可以方便一些的工具。
希望大佬可以加加一个这个功能。

**Comment by Scighost** [comment]
建议你把这个网址加入到网页小工具中
https://bbs.mihoyo.com/ys/obc/channel/map/193
