### ISSUE TITLE
快速启动游戏按钮

### ISSUE THREAD

**Issue by jiuerd** [Scighost/Xunkong#23]
因为现在的快速启动只能在win10上使用，希望能在主界面得侧边栏增加一个启动游戏的按钮，就在壁纸下边。

**Comment by Scighost** [comment]
图呢？

**Comment by jiuerd** [comment]
> 图呢？
win11没法快速启动游戏
![Snipaste_2022-03-12_18-23-41](https://user-images.githubusercontent.com/4180650/158014350-f0170ea2-ba86-49a1-90a1-5da1bfe5920c.jpg)
放在这里面会方便一点。
![Snipaste_2022-03-12_18-23-12](https://user-images.githubusercontent.com/4180650/158014344-08de7b6e-cd39-483a-8c4d-101d16256822.jpg)

**Comment by Scighost** [comment]
可能是目标系统版本的问题，下个版本我先尝试修改目标版本到22000。
继续在左侧底部加菜单对小屏不太友好。

**Comment by Scighost** [comment]
更新并启动一次后，应该就有启动游戏的按键了
