### ISSUE TITLE
导入刻晴牛杂店的祈愿记录json文件失败

### ISSUE THREAD

**Issue by alleblue** [Scighost/Xunkong#25]
![image](https://user-images.githubusercontent.com/80149512/158111048-0da4bb18-9aed-4889-935f-24715731b621.png)
错误提示如上，请问怎么解决？

**Comment by TheTychoStar** [comment]
我也一样，json不行，excel也不行，同样的错误提示。

**Comment by SCCCyy** [comment]
我也是这个问题，查看文档log文件，发现了一个错误代码，百度代码后发现是一个DLL文件错误了，然后就找不到解决办法了
ps：文件我删了，你们可以自己看看给开发者提交一下

**Comment by Scighost** [comment]
数据库限制了所有字段必须有值，看一下导入的文件中有没有字段为 null ，一般是 lang ，值改为 zh-cn 。

**Comment by TheTychoStar** [comment]
> 数据库限制了所有字段必须有值，看一下导入的文件中有没有字段为 null ，一般是 lang ，值改为 zh-cn 。

果然是这样，把所有null替换成"zh-cn"以后可以了。谢谢！

**Comment by alleblue** [comment]
解决了，谢谢

> 数据库限制了所有字段必须有值，看一下导入的文件中有没有字段为 null ，一般是 lang ，值改为 zh-cn 。
