### ISSUE TITLE
没有找到cookie_token

### ISSUE THREAD

**Issue by SSSSHM39** [Scighost/Xunkong#26]
米游社的cookie中只有ltoken，不是同一个吗

**Comment by blyc** [comment]
网页端退出 重新输账密登录

**Comment by TechOtakupoi233** [comment]
https://github.com/Scighost/Xunkong/issues/28#issuecomment-1068838888

**Comment by SSSSHM39** [comment]
已解决，重新登陆后就有了，整段复制
