### ISSUE TITLE
edge浏览器cookie无法导入

### ISSUE THREAD

**Issue by C3067721247** [Scighost/Xunkong#28]
![image](https://user-images.githubusercontent.com/84183786/158394657-8f8c1518-ab2f-4abe-87ee-d7cadf635978.png)
edge浏览器无法直接导出cookie，只能复制cookie_ token的值，第三方插件也导出不了，输入cookie_ token的值一直都是-100错误

**Comment by Fachep** [comment]
切到网络选项卡刷新页面，然后打开第一个请求，把cookie复制下来

**Comment by hhhqpalzm** [comment]
> 切到网络选项卡刷新页面，然后打开第一个请求，把cookie复制下来

复制下来了。。。现在只有个Itoken = =

**Comment by blyc** [comment]
> 

网页端退出 重新输账密登录

**Comment by hhhqpalzm** [comment]
> > 
> 
> 网页端退出 重新输账密登录

!谢谢大大！有了！
![image](https://user-images.githubusercontent.com/30164125/158521395-06282ee3-2e2a-45e1-a7d3-525ef1a2b96f.png)

**Comment by TechOtakupoi233** [comment]
亲测只复制cookie_token的值不行，我把整个cookie都复制下来就成功了
