### ISSUE TITLE
从0.1.1.0更新到0.1.2.0 win10实时便签没啦 怎么开关都调不出来

### ISSUE THREAD

**Issue by hhhqpalzm** [Scighost/Xunkong#29]
从0.1.1.0更新到0.1.2.0 win10实时便签没啦 怎么开关都调不出来 能不能给个开关或者刷新或者添加按钮 = =  找了半天 重装也不出来

**Comment by hhhqpalzm** [comment]
第一次安装寻空 在win10菜单界面可以有一个点一下就刷新的小便签 有 当前体力 何时满 还有委托完成时间的那个
更新成新版本之后就没了  重装老版本也没有  我换了台别人的电脑安装也没有 也不知道自己当时咋个搞出来的
求作者大大给个教程或者来个按钮激活吧！感谢啦！呜呜呜

**Comment by Scighost** [comment]
![image](https://user-images.githubusercontent.com/61003590/158515995-0ce94ce8-c7ef-4aaf-8909-13c9a065fdbf.png)

**Comment by hhhqpalzm** [comment]
> ![image](https://user-images.githubusercontent.com/61003590/158515995-0ce94ce8-c7ef-4aaf-8909-13c9a065fdbf.png)

谢谢大大！！！！有了！找到了！
![image](https://user-images.githubusercontent.com/30164125/158521343-872433b7-a803-4cab-ade1-b98063031921.png)
