### ISSUE TITLE
【祈愿记录】小保底与大保底未被正确识别

### ISSUE THREAD

**Issue by xfl03** [Scighost/Xunkong#32]
# BUG反馈
相关截图：
<img width="1024" alt="BUG" src="https://user-images.githubusercontent.com/3205159/158612706-86588c09-7d10-4ab5-83ca-16b33d610b1e.png">

以活动祈愿为例，预期效果：
- 已垫**小**保底内46抽
- 平均UP五星所用抽数**53.33**
- 小保底不歪**3**
- 小保底歪**0**
- 五星记录显示3个彩色（代表小保底）

# 补充信息
- 使用的版本：0.1.2.0（目前最新）
- 操作系统：Windows 10
- 游戏服务器：国服/国际服都有一样的问题

**Comment by xfl03** [comment]
# 问题分析
作者似乎还没回复，我不太会C#，也装不下VS，随便看了一下相关代码，整理一下相关思路：
- 判断是否为Up角色的逻辑在`Xunkong.Desktop.Services.WishlogService.GetWishlogItemExByUidAsync`，这个方法会将用户的祈愿记录与祈愿MetaData中的Up数据进行比较
- 祈愿活动相关的MetaData是通过方法`Xunkong.Desktop.Services.XunkongApiService.GetWishEventInfosFromServerAsync`从`https://api.xunkong.cc/v0.1/genshin/metadata/wishevent`里获取的
- 这个方法唯一使用的地方在`Xunkong.Desktop.ViewModels.WishlogSummaryViewModel.WishlogSummaryViewModel.GetMetadataAsync`，这个方法需要用户手动点击`更新元数据`按钮

简而言之，如果用户没有手动点击`更新元数据`按钮，就使用`祈愿记录`功能，会导致显示异常且无任何提示。

# 建议修复方式
虽然看代码中有提示`首次使用或卡池更新后记得「更新元数据」`，但实际使用过程中并没有见到这个提示，建议将这一更新过程自动化：

- 当用户抽卡记录不符合任何一个祈愿活动时，说明MetaData可能过期，此时可以尝试自动更新MetaData

具体的修复方式还请作者定夺。

**Comment by Scighost** [comment]
提示 `首次使用或卡池更新后记得「更新元数据」` 只有点击关闭后下次才不会弹出，可能你那儿遇到 bug 了（现阶段 WinUI3 的问题很多）。使用手动更新有两方面的考虑：

- 在没有抽卡记录的时候可以查看卡池
- 减轻服务器的压力

现在我已使用 Cloudflare 代理全部流量，无需再考虑服务器的压力，所以我认为可以改用以下方案：

- 数据库的元数据表中没有任何数据
- 最新的抽卡记录超出已有卡池信息

当满足上述任意条件时，自动更新元数据并提醒用户 `刷新界面` ，同时保留 `手动更新元数据` 按键。
