### ISSUE TITLE
游戏开启状态下无法更新祈愿记录

### ISSUE THREAD

**Issue by TheTychoStar** [Scighost/Xunkong#35]
提示日志文件被其他进程占用，但是以前的刻记牛杂没有这个限制。
![error](https://user-images.githubusercontent.com/75252778/158765036-c4052f38-931b-416d-97c1-d4e3c02dbc76.jpg)
。

**Comment by Scighost** [comment]
无法复现此问题，相关代码和刻记牛杂店一样。
https://github.com/Scighost/Xunkong/blob/1d8278ddc977f6b586bce3667937c2024fc3f9ae/src/Desktop/Desktop/Services/WishlogService.cs#L98

**Comment by TheTychoStar** [comment]
好奇怪，不能启动游戏的问题也很奇怪，我试一下卸载重装吧。

**Comment by Lightczx** [comment]
> 无法复现此问题，相关代码和刻记牛杂店一样。
> 
> https://github.com/Scighost/Xunkong/blob/1d8278ddc977f6b586bce3667937c2024fc3f9ae/src/Desktop/Desktop/Services/WishlogService.cs#L98

可以使用 File.Open 的 包含 FillShare 的 重载
