### ISSUE TITLE
如何再次调出启动欢迎界面？使用的windows 11字体是哪一个？

### ISSUE THREAD

**Issue by TheTychoStar** [Scighost/Xunkong#37]
系统Windows 10，在欢迎界面安装了新字体以后显示正常了。但关闭应用再启动时显示又不正常了，想要重新安装字体，发现找不到在哪里能重新开启欢迎界面了。字体的名字也没记住，没法去搜索。

**Comment by Scighost** [comment]
> 如何调出欢迎界面？

卸载重装

> 字体是哪个？

`Segoe Fluent Icons.ttf`
https://file.xunkong.cc/download/font/Segoe%20Fluent%20Icons.ttf
