### ISSUE TITLE
【开发环境】指引有待完善&无法完成构建

### ISSUE THREAD

**Issue by xfl03** [Scighost/Xunkong#38]
# 【开发环境】指引有待完善&无法完成构建
刚才写了好多话，被GitHub 500吃掉了，我长话短说。

## 指引有待完善
除了`README.md`里的那些，还需要安装`Windows 11 SDK (10.0.22000.0)`

## 无法完成构建
最新的[commit](https://github.com/Scighost/Xunkong/commit/1d8278ddc977f6b586bce3667937c2024fc3f9ae#diff-146eb24a0c79cac95db3ea3b6355a4e577e01aeeb56079fb3d2b8c2ac4f95b50L19)删除了`CharacterInfo.NameTextMapHash`，但是[使用的地方](https://github.com/Scighost/Xunkong/blob/main/src/Desktop/Desktop/Toolbox/KeqingNiuzaMetadataTool.xaml.cs#L86)没改，还在用这个字段，导致没法构建。

**Comment by Scighost** [comment]
前几天刚把目标框架升级到了22000，readme还没更新，不过生成的时候应该会有安装提示，问题不大。
这次commit修改了webapi和对应的数据结构，桌面端还没有修改，建议生成时选择最后一个有tag的版本。

**Comment by Scighost** [comment]
commit [desktop: update database and package reference](https://github.com/Scighost/Xunkong/commit/5ca872e17a527e27b0d6fabb48c10bc218442c84)

**Comment by xfl03** [comment]
@Scighost 
不好意思再打扰一下作者，想请教一下如何关闭开发环境的证书校验呀，现在构建会报错`未通过所提供的指纹 09188B610F483A0C7BF46142AC329CC22CCAA7B6 找到任何证书`

**Comment by Scighost** [comment]
因为我不可能把自签名证书传上来，也不能泄漏密码

**Comment by xfl03** [comment]
> 因为我不可能把自签名证书传上来，也不能泄漏密码

是啊，所以得提醒一下后人要自己创建一个证书
