### ISSUE TITLE
右上角四个键无法点击

### ISSUE THREAD

**Issue by Scighost** [Scighost/Xunkong#44]
> 微软坑人！
### 原因
使用应用商店更新了 WindowsAppRuntime.Main.1.0 的用户会遇到这个问题。
### 解决方案
没有

**Comment by Klamist** [comment]
用powershell敲指令卸载这个包？

**Comment by Scighost** [comment]
参考 https://github.com/microsoft/microsoft-ui-xaml/issues/6858

**Comment by Scighost** [comment]
0.1.4.0 版本已适配 WindowsAppSdk v1.0.1。
0.1.4.0 版本之前**更新了** WindowsAppRuntime.Main.1.0 会遇到这个问题；
0.1.4.0 版本及以后**不更新** WindowsAppRuntime.Main.1.0 会遇到这个问题。
商店更新链接 https://www.microsoft.com/store/productId/9PCMPL33XP5M
