### ISSUE TITLE
更新弹窗不显示下载按键问题未解决

### ISSUE THREAD

**Issue by MaxwellYe0815** [Scighost/Xunkong#45]
打开寻空时自动弹出的更新提醒无下载按键
手动检查更新正常
![image](https://user-images.githubusercontent.com/64358442/159221545-37fc2c3b-481a-46f4-a488-38d736e0c364.png)

**Comment by MaxwellYe0815** [comment]
#13

**Comment by Scighost** [comment]
在设置界面检查更新

**Comment by Scighost** [comment]
刚才没仔细看描述，这个问题在 0.1.3.0 版本才解决
