### ISSUE TITLE
交互问题：需要一个启动按钮

### ISSUE THREAD

**Issue by Haku247** [Scighost/Xunkong#46]
提议在侧边栏直接增加一个启动游戏的按钮，win11没法右键磁铁启动游戏。
只能每次打开应用->侧边栏->工具箱->启动游戏 (是的，我很懒

另外请教一个问题,我使用playnite管理游戏，启动寻空需要一个启动命令，我应该如何填写下面这个表呢？

![image](https://user-images.githubusercontent.com/20238213/159411493-2ab5458a-1d08-4a36-b43e-2a9d0f275152.png)

我尝试过直接启动WindowsApps下的应用壳内的x64/xunkong.desktop/Xunkong.Desktop.exe,但是无响应

**Comment by Scighost** [comment]
理论上只要启动过一次应用，在开始菜单的寻空图标上（不是磁贴）点击右键就会出现启动游戏的操作。

**Comment by Haku247** [comment]
![image](https://user-images.githubusercontent.com/20238213/159428736-ea4e2d0d-9087-4ca0-a633-1addfdd91748.png)

**Comment by Scighost** [comment]
我先装个win11测试一下

**Comment by Scighost** [comment]
系统已崩，没法测试了

**Comment by Haku247** [comment]
额，你搞个虚拟机跑一下就行= =
