### ISSUE TITLE
平均UP五星所用抽数∞、角色/武器活动祈愿界面为空

### ISSUE THREAD

**Issue by Xm798** [Scighost/Xunkong#5]
![image](https://user-images.githubusercontent.com/48074861/156096852-0c251e9f-f793-4a9d-8ed2-ac2f2a078eb7.png)

![image](https://user-images.githubusercontent.com/48074861/156096933-a973709c-e008-4f7f-a8f8-196096d5dda6.png)

**Comment by Scighost** [comment]
点击右上角的更新元数据就能解决问题

**Comment by Xm798** [comment]
已点击，仍为∞和空白
![image](https://user-images.githubusercontent.com/48074861/156098712-ebd8e769-9d83-4bdc-9def-3ca5cc7ef2c2.png)
![image](https://user-images.githubusercontent.com/48074861/156098743-71371837-7066-4cf4-aea5-0f2a065197f9.png)

**Comment by Xm798** [comment]
> 已点击，仍为∞和空白 ![image](https://user-images.githubusercontent.com/48074861/156098712-ebd8e769-9d83-4bdc-9def-3ca5cc7ef2c2.png) ![image](https://user-images.githubusercontent.com/48074861/156098743-71371837-7066-4cf4-aea5-0f2a065197f9.png)

更新：重启后可以了

**Comment by Scighost** [comment]
刷新页面了吗

**Comment by Xm798** [comment]
> 

忘记了TAT 直接重启了
