### ISSUE TITLE
希望添加客户端切换功能

### ISSUE THREAD

**Issue by citydirector** [Scighost/Xunkong#51]
希望添加客户端切换功能，切换官服、B服、国际服
（日常干翻原plus）

**Comment by Scighost** [comment]
我没有这个需求。
如果你能定期维护需要替换的文件，我可以考虑加上。

**Comment by citydirector** [comment]
> 我没有这个需求。 如果你能定期维护需要替换的文件，我可以考虑加上。

官服和B服切换只需要改Genshin Impact(Yuanshen.exe同目录下)的config.ini就可以了，替换文件是国服和国际服切换时需要替换部分文件。

**Comment by citydirector** [comment]
维护替换文件倒是没问题，但不是很会用github

**Comment by Scighost** [comment]
客户端转换很麻烦，不会加入这个功能。
