### ISSUE TITLE
【建议】 祈愿记录Excel导出功能

### ISSUE THREAD

**Issue by benbenlike** [Scighost/Xunkong#54]
### 问题描述
有时想导出祈愿记录自己做Excel分析 or 导入其他工具 or 留档

### 解决方案
希望添加祈愿记录Excel导出功能

### 补充信息
无

**Comment by Scighost** [comment]
暂时不想做这个功能，你可以自行从数据库中导出数据。

**Comment by Scighost** [comment]
已实现，下个版本发布
046a6fc8a01e9bacb6ca0c5ad2ba6bcb3a07e6b1
