### ISSUE TITLE
【反馈】 0.1.4.0安装错误：应用程序无法安装应用包相关项，请向开发人员索要 应用包。

### ISSUE THREAD

**Issue by Haku247** [Scighost/Xunkong#55]
完整的反馈信息可以帮你快速解决问题

### 问题描述
 0.1.4.0安装错误：应用程序无法安装应用包相关项，请向开发人员索要 应用包。

### 复现步骤
更新报错

### 预期行为
正常安装

### 截图
![image](https://user-images.githubusercontent.com/20238213/160251530-bf185bc9-16bd-4f96-a041-6af183b5acde.png)

### 系统及寻空版本
- 系统：Windows 11 专业工作站版本 21H2 22000.556
- 寻空：0.1.3.0

### 日志
nothing.

### 补充信息
nothing.

**Comment by Scighost** [comment]
应用安装程序出问题太正常不过了。
可以尝试使用 power shell 安装，如果这样都安装不了，我也没办法。

**Comment by Haku247** [comment]
0.1.4.3已可以正常安装。
