### ISSUE TITLE
【建议】增加祈愿记录删除功能

### ISSUE THREAD

**Issue by Demooed** [Scighost/Xunkong#58]
牛杂店里有一个删除uid账号的功能，希望在寻空里加入，删除uid账号的同时删除祈愿记录。

**Comment by Demooed** [comment]
暂时找到了解决办法，删除文档下的xunkong文件夹，不过还是希望能在app内操作

**Comment by Scighost** [comment]
已实现，下个版本发布
046a6fc8a01e9bacb6ca0c5ad2ba6bcb3a07e6b1
