### ISSUE TITLE
【建议】 不用每日一图，但希望能设定固定的背景图片

### ISSUE THREAD

**Issue by anhcemi** [Scighost/Xunkong#62]
### 问题描述
开了“不显示每日一图”功能之后，背景直接就是空白了。

### 解决方案
简单点就是关闭每日一图功能后，壁纸就锁定成关闭之前的最后一张图
复杂点就是能自己选择图（我本来想自己去改背景图片文件的，但是只找到了各种logo和element图- -）

另外就是每日一图功能本身的弊端，每次打开软件都会先是全白/纯黑的，然后才能加载出图片。
我CPU是5900，宽带300M，内存也是正常的3200的16G双通道，刚打开软件背景是空白/纯黑，加载出图片大概要3-4s，有点过于慢了。以我的猜想，设置本地壁纸的话应该会好不少？

**Comment by Scighost** [comment]
每次打开软件都需要从服务器获取当前的推荐壁纸，没有缓存的话还需要再下载，确实需要较长的时间。

针对自定义壁纸的功能，我的实现方法如下：
**关闭**每日一图功能后，把你的图片文件拖到下面这个位置即可。
![image](https://user-images.githubusercontent.com/61003590/160860990-f2e08acf-c78d-423f-bd9f-1ff3c948a37c.png)

**不关闭**的状态下也会把拖入的图片当作壁纸，但是下次启动时则恢复至推荐图。

**Comment by Scighost** [comment]
忘了说，功能于 0.1.4.3 版本实现，大约十几分钟后会收到更新。
