### ISSUE TITLE
【反馈】 建议增加删除某个账号祈愿记录的功能

### ISSUE THREAD

**Issue by Xm798** [Scighost/Xunkong#63]
### 问题描述

目前没有祈愿记录删除功能，在更新祈愿记录后出现了数据重复的问题，猜测是由于我的数据在Wishexport Snap和刻记之间通过 UIGF导入导出而各个工具对 UIGF 的支持不完美造成的，因此我尝试从刻记导出一份数据后导入寻空，但数据直接 double 更加错乱了……由于寻空采用 sqlite 作为数据库，并不能像之前一样方便的通过删除本地文件清空某个账号的祈愿记录，对于不熟悉数据库操作的用户来说难以删除某个特定账号数据，因此需要该功能。

![image](https://user-images.githubusercontent.com/48074861/160967908-6e609d6d-638a-402a-8141-74baf23bf0e9.png)

### 解决方案

增加删除某个账号祈愿记录的按钮

**Comment by Scighost** [comment]
已实现，下个版本发布
046a6fc8a01e9bacb6ca0c5ad2ba6bcb3a07e6b1
