### ISSUE TITLE
【建议】现在网页版米游社无法获取cookie_token，请问怎么办

### ISSUE THREAD

**Issue by Frank-mdai** [Scighost/Xunkong#64]
### 问题描述

现在网页版米游社无法获取cookie_token

我拿到的格式如下：
_MHYUUID=***; UM_distinctid=***; _ga=***; mi18nLang=zh-cn; ltuid=***; login_uid=***; ltoken=***; CNZZDATA1275023096=***; _gid=***; login_ticket=***; _gat=1

这里面没有cookie_token，一直在报错---HoyolabException 请先登录 (-100)

### 解决方案

希望能利用一下这个格式……或者指个路，是不是手机可以查到cookie_token？

**Comment by Demooed** [comment]
https://bbs.mihoyo.com/ys/ 到这个网址里面登录 是能获取到cookie_token的

**Comment by Frank-mdai** [comment]
非常感谢，修了半天发现只要开隐身窗口就能解决
