### ISSUE TITLE
【反馈】 小地图的更新日志无法关闭

### ISSUE THREAD

**Issue by XBCoder128** [Scighost/Xunkong#66]
### 问题描述
第一次打开小地图，会有一个更新日志以及人员名单，该名单无法关闭

### 截图
![image](https://user-images.githubusercontent.com/24350033/161262989-c4f6f6da-57ea-426c-a8aa-725f04c364bf.png)
提交截图有助于分析问题

### 系统及寻空版本

- 系统：
- 寻空：

**Comment by YangAoLib** [comment]
可以通过, Ctrl+鼠标滚轮 来缩放, 之后便可以关闭了
将鼠标放在非地图主体部分可以再缩放回去
