### ISSUE TITLE
【反馈】 角色信息 雷电将军 多了一个无用的固有天赋

### ISSUE THREAD

**Issue by Askwind** [Scighost/Xunkong#70]
### 问题描述

雷电将军 多了一个无用的固有天赋

### 预期行为

一般都是三个固有天赋

### 截图

![BUG-微信截图_20220402104059](https://user-images.githubusercontent.com/13656212/161362736-a8f4e500-c85e-4e04-98c1-b555031b0562.png)

### 系统及寻空版本

- 系统：Windows 10 家庭版 20H1
- 寻空：0.1.5.0

### 日志

日志位于 `我的文档\Xunkong\Log`，上传前注意**删除个人信息**

**Comment by Scighost** [comment]
你点一下就知道这是是啥了

**Comment by Askwind** [comment]
好吧~不能料理 也算是特殊体质了。mhy把心海的-100%写出来了， 雷电的却没写
