### ISSUE TITLE
【反馈】 Dependencies\x64下依赖包无法安装

### ISSUE THREAD

**Issue by WatchKitty** [Scighost/Xunkong#71]
### 问题描述

安装Microsoft.VCLibs.x64.14.00.appx 时提示
应用安装失败，错误消息: 错误 0x80073D02: 无法安装，因为需要关闭以下应用: MicrosoftWindows.Client.CBS_120.2212.4170.0_x64__cw5n1h2txyewy。 (0x80073d02)

安装Microsoft.VCLibs.x64.14.00.Desktop.appx 时提示
应用安装失败，错误消息: 错误 0x80073D02: 无法安装，因为需要关闭以下应用: Microsoft.DesktopAppInstaller_1.17.10271.0_x64__8wekyb3d8bbwe。 (0x80073d02)

### 复现步骤
双击打开appx

### 预期行为
安装成功

### 截图
![应用安装程序 2022_4_2 15_56_17](https://user-images.githubusercontent.com/63351588/161373114-7c6d95e0-a1d7-4571-898f-766d7387031d.png)

![应用安装程序 2022_4_2 15_56_48](https://user-images.githubusercontent.com/63351588/161373124-30532984-f143-411e-8dc0-f9058d59f5ba.png)

### 系统及寻空版本

- 系统：Windows10 Home 21H2
- 寻空：0.1.5.0

### 日志

无

**Comment by Scighost** [comment]
微软的问题，寻空不背锅
