### ISSUE TITLE
【反馈】 多账号管理不可用

### ISSUE THREAD

**Issue by zangxycoding** [Scighost/Xunkong#72]
点击添加就报这个错误  
 
![image](https://user-images.githubusercontent.com/17939214/161395723-d057b890-fa83-49ed-aab1-fb66e1b6b0ca.png)

**Comment by Scighost** [comment]
检查一下注册表的这个值
计算机\HKEY_CURRENT_USER\SOFTWARE\miHoYo\原神\MIHOYOSDK_ADL_PROD_CN_h3123967166

**Comment by zangxycoding** [comment]
![image](https://user-images.githubusercontent.com/17939214/161411742-57b47f55-7969-465f-81ca-acbe8580dde0.png)
这个值正常啊 

把注册表清空了再登录也不行

**Comment by Samonyoge** [comment]
遇到相同问题。同时正在使用PLUS启动器的多账号功能，可正常使用，不知道是否与之有关/冲突

**Comment by Scighost** [comment]
已经修复，但未发布

**Comment by Samonyoge** [comment]
谢谢
