### ISSUE TITLE
【反馈】小地图白屏无法显示地图

### ISSUE THREAD

**Issue by Askwind** [Scighost/Xunkong#74]
小地图白屏无法显示地图，不管是在游戏中用快捷键打开 ，还是用程序自带的按钮启动
### 问题描述

小地图窗口内白屏，无法显示地图

### 复现步骤

打开寻空-启动游戏-打开小地图

### 预期行为
打开小地图窗口内显示正确的地图

### 截图

![image](https://user-images.githubusercontent.com/13656212/161443772-b6ae6b8e-6233-4930-9657-6df30da4cdff.png)

### 系统及寻空版本

- 系统： Windows 10 专业版 20H1
- 寻空：0.1.5.2

### 日志

日志位于 `我的文档\Xunkong\Log`，上传前注意**删除个人信息**

**Comment by Askwind** [comment]
我已经进行了更新数据库 以及 清理图片缓存的操作，也没能解决问题

**Comment by Scighost** [comment]
有没有可能你没有安装 WebView2

**Comment by Askwind** [comment]
![image](https://user-images.githubusercontent.com/13656212/161559220-8b0bf7f1-7e27-4590-9818-668a229cd431.png)

从99版更新到100版就可以……
