### ISSUE TITLE
【建议】 希望添加米游社签到状态显示功能

### ISSUE THREAD

**Issue by YangAoLib** [Scighost/Xunkong#75]
在实时便签中显示米游社签到状态

### 问题描述

总是会忘记签到, 因为系统无法正确的自动签到, 所以希望有签到状态提醒, 以辅助主动签到

### 解决方案

在实时便签中显示米游社签到状态

**Comment by Askwind** [comment]
在 设置——功能——米游社签到 ，自动签到功能我用着很ok

**Comment by YangAoLib** [comment]
> 

你平时是怎么使用的呢

**Comment by YangAoLib** [comment]
> 在 设置——功能——米游社签到 ，自动签到功能我用着很ok

你平时是怎么使用的呢

**Comment by Askwind** [comment]
> > 在 设置——功能——米游社签到 ，自动签到功能我用着很ok
> 
> 你平时是怎么使用的呢

1.打开寻空
2.角色登录到寻空
3.等待一个时间间隔（默认2分钟）或者手动点击签到
搞定！

**Comment by Scighost** [comment]
启动时会自动签到，如果出错有横幅提醒，已签到过则不会重复签到。
没有必要再加签到状态的标志。
