### ISSUE TITLE
【反馈】 0.1.7.0深境螺旋显示bug

### ISSUE THREAD

**Issue by Frank-mdai** [Scighost/Xunkong#78]
### 问题描述

0.1.7.0深境螺旋显示bug

即：战斗数据→最多击破数，调用了“最强一击”的伤害值，应该是手滑复制粘贴的时候搞错了，人物的话我不知道有没有错

顺便说一下我无法看到左边的图标，上面的主页/相册/祈愿记录/角色信息/旅行札记 的对应图标都看得到

### 复现步骤

运行→（主要功能）深境螺旋→20XX年X月X→战斗数据

### 预期行为

最多击破数，应为击破数字而不是伤害值

### 截图

![image](https://user-images.githubusercontent.com/42663137/163320267-f7bcb74a-ddf2-4311-aae0-aefa54cc5cf9.png)

### 系统及寻空版本

- 系统：Windows 10
- 寻空：0.1.7.0

### 日志

感觉可以不发？

### 补充信息

非常抱歉写了一堆废话

**Comment by Frank-mdai** [comment]
其实还有一点，旅行札记的月趋势有点不对劲，一并发一下吧
![image](https://user-images.githubusercontent.com/42663137/163320492-47f7544c-b186-4dd9-8833-58c40dc1d78f.png)

**Comment by Scighost** [comment]
最多击破数那确实写错了；
深境螺旋的图标是一张白色的图，在黑暗模式下能看到；
月趋势没有问题，相比于上月减少了56%，你需要获取近三个月的记录才能看到更多内容。
