### ISSUE TITLE
添加小工具时出现错误

### ISSUE THREAD

**Issue by PurBlu** [Scighost/Xunkong#8]
可能是一个比较个人的Issue😉
Paimon.moe这个网站一直在用 但似乎国内大部分地区的DNS服务器解析不了 也不想随时挂梯
于是自己找了个裸连也可ping通的IP然后放进host  cmd中刷新了DNS缓存
![image](https://user-images.githubusercontent.com/74239692/157166466-961d67e7-377b-45c9-b0f8-596b9d5292b8.png)

现在的结果是Edge已经能打开了 但是寻空报错
![image](https://user-images.githubusercontent.com/74239692/157166306-dd78a14a-41d9-45c5-b2fc-ed798dd8e041.png)

**Comment by Scighost** [comment]
获取图标和网站标题的时候出错了，你自己填一下两栏信息吧

**Comment by PurBlu** [comment]
![image](https://user-images.githubusercontent.com/74239692/157186875-643cbdb2-47a7-4e27-8a42-5747d1d75f86.png)
确实可能还是网络环境的问题 索性把icon扔图床上了
