### ISSUE TITLE
安装不了，已经根据教程安装了

### ISSUE THREAD

**Issue by JuLi-C** [Scighost/Xunkong#80]
点击 使用 PowerShell 运行
这一步直接就是一闪而过没有什么提示

**Comment by Sakurakouji-Runa** [comment]
试试直接双击[msixbundle](https://github.com/Scighost/Xunkong/releases/download/0.1.7.0/Xunkong.Desktop.Package_0.1.7.0_x64.msixbundle)安装？

**Comment by JuLi-C** [comment]
不行啊，签名我也装了，显示这样



---原始邮件---
发件人: "桜小路 ***@***.***&gt;
发送时间: 2022年4月16日(周六) 下午5:51
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [Scighost/Xunkong] 安装不了，已经根据教程安装了 (Issue #80)




 
试试直接双击msixbundle安装？

**Comment by JuLi-C** [comment]
显示这样：无法验证此应用包的发布者证书。请与系统管理员或应用开发人员联系，以获取具有验证证书的新应用包。必须验证应用包中签名的根证书和所有直接证书(0x800B010A)

**Comment by Scighost** [comment]
给出的有用信息实在太少，只能把文档扔给你
https://xunkong.cc/release/desktop/download

**Comment by JuLi-C** [comment]
> 给出的有用信息实在太少，只能把文档扔给你 https://xunkong.cc/release/desktop/download
[](https://cdn.jsdelivr.net/gh/JuLi-C/lsjhxuds@main/yuyuren/Snipaste_2022-04-16_19-13-53.png)

**Comment by JuLi-C** [comment]
[](https://cdn.jsdelivr.net/gh/JuLi-C/lsjhxuds@main/yuyuren/Snipaste_2022-04-16_19-13-53.png)

**Comment by JuLi-C** [comment]
https://cdn.jsdelivr.net/gh/JuLi-C/lsjhxuds@main/yuyuren/Snipaste_2022-04-16_19-13-53.png

**Comment by JuLi-C** [comment]
> 给出的有用信息实在太少，只能把文档扔给你 https://xunkong.cc/release/desktop/download
大佬我试了一下，公司的win10安装没问题，我的win11测试版安装不行

**Comment by ZoftTy** [comment]
windows 11 什么版本？我自己在 window 11 22000.613 可以安装。

**Comment by Sakurakouji-Runa** [comment]
你去设置里把这个开关打开，然后再用PowerShell安装试试？
![Snipaste_2022-04-17_21-18-30](https://user-images.githubusercontent.com/46081776/163716125-0c2a4e6c-9ab7-42f6-9f77-01cb0895adee.png)

**Comment by JuLi-C** [comment]
> 你去设置里把这两个开关打开，然后再用PowerShell安装试试？ ![Snipaste_2022-04-17_21-24-06](https://user-images.githubusercontent.com/46081776/163716300-be3ea3e8-c5fb-4bd8-903b-cb82557c51ec.png)

确实是这个原因，打开就好了

**Comment by JuLi-C** [comment]
> windows 11 什么版本？我自己在 window 11 22000.613 可以安装。

已经安装好了

**Comment by Scighost** [comment]
完善文档 [xunkong/docs](https://github.com/xunkong/docs/commit/6ee6868a0cd4e97c34902ae34f54295473627890)
