### ISSUE TITLE
【反馈】 角色一览统计有误

### ISSUE THREAD

**Issue by Xm798** [Scighost/Xunkong#84]
### 问题描述

角色一览显示的统计数据有误。卡池统计正确，角色活动祈愿正确。

### 截图

![image](https://user-images.githubusercontent.com/48074861/163705494-97fe657f-04eb-4d77-bd1f-af51a1837138.png)

![image](https://user-images.githubusercontent.com/48074861/163705506-49a0a31a-52fa-475e-a086-1e1121dd5534.png)

### 系统及寻空版本

- 系统：Windows 11 21H2 22000.613
- 寻空：0.1.7.1

**Comment by Scighost** [comment]
你给出的有用信息太少了，最好把记录文件导出后发给我

**Comment by Xm798** [comment]
> 你给出的有用信息太少了，最好把记录文件导出后发给我

发现问题了，原始数据中出现了 id 不同但是是同一条记录的数据，但在角色活动祈愿中是正常的。不太清楚这个重复记录是怎么来的……233 原始文件已经发送到您的邮箱
![image](https://user-images.githubusercontent.com/48074861/163705860-68d75590-c7df-4ada-b9b1-de9f50e513f8.png)

**Comment by Scighost** [comment]
你的记录挺好解决重复问题，全部都有 id，只是多了一部分没 id 的数据，把多的部分删掉就行了。

在导出的 excel 文件的**原始数据**表中找到 `id` 这一列，删除以 `101023` 开头的所有行。

**Comment by Xm798** [comment]
好耶，解决了，谢谢！
