### ISSUE TITLE
从Excel文件导入数据后无卡池统计信息

### ISSUE THREAD

**Issue by Xm798** [Scighost/Xunkong#9]
当前版本 0.1.0.0，已尝试更新元数据、已尝试刷新页面、已尝试重启 APP，问题依然存在，如图所示：
![image](https://user-images.githubusercontent.com/48074861/157235743-23a04ed0-2038-4ac1-b9a5-fe2bf8e57189.png)

**Comment by Scighost** [comment]
是用 excel 导入的吗？
看一下 `我的文档/ Xunkong/Data/XunkongData.db` 数据库的 `Wishlog_Items` 表中的 `QueryType` 字段；
这个值应该和 `WishType` 相对应，规则如下：

|WishType|QueryType|
|---|---|
|100|100|
|200|200|
|301|301|
|302|302|
|400|301|

**Comment by Xm798** [comment]
是从 Excel 导入，数据库中 QueryType 字段为 0。
![image](https://user-images.githubusercontent.com/48074861/157251856-eaf84f0d-0666-472f-b698-6d4172debff8.png)

**Comment by Xm798** [comment]
修改数据库添加了 QueryType 后正常了

--------------原始邮件--------------
发件人："Scighost ***@***.***&gt;;
发送时间：2022年3月8日(星期二) 晚上10:21
收件人："Scighost/Xunkong" ***@***.***&gt;;
抄送："Xm798 ***@***.***&gt;;"Author ***@***.***&gt;;
主题：Re: [Scighost/Xunkong] 从Excel文件导入数据后无卡池统计信息 (Issue #9)
-----------------------------------

 

 
可以自行加上QueryType，也可以使用json再导入
